### PR TITLE
Add Color support (fixes #16)

### LINKED ISSUE #16: Color image support
Cont. #14 

metrics from Distances.jl needed to be tested to support color image inputs. 

Unless explicitly stated, the distances are the sum of channelwise distances, and mean/normalized distances are divided by `num_pixel*num_channel`.

That's to say, `ssdn` in `Images.jl` is not defined correctly for `Color3` Images
```julia
"`s = ssdn(A, B)` computes the sum-of-squared differences over arrays/images A and B, normalized by array size"
ssdn(A::AbstractArray{T}, B::AbstractArray{T}) where {T} = ssd(A, B)/length(A)
```

cc @timholy

### PR DESCRIPTION
**Pull request by johnnychen94**
The following distances supports `Color3` image input:

* `SqEuclidean`
* `Euclidean`
* `Cityblock`
* `Minkowski`
* `Hamming`
* `TotalVariation`

By default, each pixel is treated as a 3d point. If we want to calculate the channelwise distances, we can `channelview(a)` first.

As for other distances:

* `Hausdorff` distance supports `Gray2dimage{Bool}` only
* `CIEDE2000` distance for `AbstractArray{<:Number}` type inputs is restricted to 2d array, which is regarded as Gray image.

### CODE REVIEW

**Comment by juliohm** [comment]
Thank you Johnny for the improvements. Just make sure that hausdorff
supports N dimensional images. It is not restricted to 2D.

Best,

**Comment by johnnychen94** [comment]
`Hausdorff` distance is quite generic as a distance between sets, but will that makes sense to images? My question is: how do we interpret 3d Gray{Bool} Images?

**Comment by juliohm** [comment]
It is defined for point sets in N dimensions. In 2D the points are the
black pixels. In 3D the points are the black voxels. Makes sense?

**Comment by juliohm** [comment]
If you are asking about the image type then we need to use a type that
supports the idea of 3 axes and then each entry is a bool value. I'm not up
to date with the image types at the moment.

**Comment by johnnychen94** [comment]
my concern is that the third channel of `AbstractArray{Gray{Bool}, 3}` can have any of the following meanings:

* time
* literally 3D image of 3D object -- Only this makes sense to `Hausdorff`
* sample: `Vector{Array{Bool, 2}}`

So I think it's better to let potential 3D-image-processing packages to do this job. How do you think?

**Comment by juliohm** [comment]
I need hausdorff in 3D in my use cases. Please do not constrain the
algorithm at this point. If there is an issue regarding the image types we
need to fix it first. I don't see how the semantics would affect the
application of the distance. The user will know when it makes sense to call
a distance on a 3D image. If any of the axes means something different that
is not a spatial coordinate he/she should not call the distance at this
point.

**Comment by johnnychen94** [comment]
Good point. Other distances have the same issues.

Bad news is these restrictions are made in the last redesign PR (not this one), and it's already tagged a release (`v0.2.2`)

I'll fix it later and bump a release.

**Comment by juliohm** [comment]
Thank you. For future reference, it is always a good idea to ask before
removing features. I've noticed that you are cleaning up the code which is
great. But sometimes it is good to check to see if people need the feature
before committing changes.

Cheers

**Comment by johnnychen94** [comment]
Sorry for bringing the trouble, didn't notice it.

Another big change is the removal of `ImagePreMetric`, `ImageSemiMetric` and `ImageMetric`.

**Comment by timholy** [comment]
> my concern is that the third channel of AbstractArray{Gray{Bool}, 3} can have any of the following meanings:

We have mechanisms in place for this already:
- time: this should be handled by the caller. In algorithms that expect image sequences, images can be "annotated" using [ImageAxes](https://juliaimages.org/ImageAxes.jl/latest/) as having a time axis. Constructs like `view(img, Axis{:time}(15))` Just Work to collect a time-slice no matter how many spatial dimensions `img` has. We do this routinely in my lab's work. (And it is one of the ways that, for certain things, JuliaImages is *way* ahead of the competition...) 
- literally 3D image of 3D object: yep, this is the default interpretation. In ImageAxes the default is to assume axes are spatial unless annotated otherwise.
- `Vector{Array{Bool, 2}}`: not sure what you mean here. In that case it's not an `AbstractArray{Bool, 3}`, no?

**Comment by johnnychen94** [comment]
Thanks for the explanation,

`Vector{Array{Bool, 2}}` is just a random collection(batch) of Array{Bool,2} images. Most deep learning frameworks interpret 4-D array with `WHCB` (width, height, channel, batch) convention.

**Comment by johnnychen94** [comment]
I'd like to merge this PR if there's no further feedback since the numerical test says it's good. Then fixes the 3D problem in the next PR.

**Comment by timholy** [comment]
> Vector{Array{Bool, 2}} is just a random collection(batch) of Array{Bool,2} images.

Right. Just saying, that's not really ambiguous because as far as Julia is concerned it's not the same as a 3d array.

> Most deep learning frameworks interpret 4-D array with WHCB (width, height, channel, batch) convention.

It would be fine to have a `whcb(img)` function which puts it in this form, but hard-coded interpretations for specific dimensionalities (or dimensions with particular sizes, as in Matlab's "anything of size 3 must be a color dimension") feels like a 1980s-era hack. GPU programming---which drives deep learning frameworks---is still pretty much using 1980s-era constructs (e.g., native 4D arrays on the GPU, anyone?), though it has improved a lot lately.

**Pull request merged**
