### PR TITLE
WIP: Add earth mover's distance

### PR DESCRIPTION
**Pull request by timholy**
This depends on the unregistered https://github.com/mirkobunse/EarthMoversDistance.jl. Issues include dependence on a C library. Thoughts?

### CODE REVIEW

**Comment by timholy** [comment]
See some discussion at https://github.com/robertfeldt/EarthMoversDistance.jl/pull/1

**Comment by juliohm** [comment]
Thank you @timholy I fully agree with the discussion you've linked. It would be nice to have a Julia implementation of EMD algorithms. I am also busy at the moment to try understand it in depth.

Do you think it is a good idea to have it here as a dependency though? My opinion is that we could make use of the unregistered package, or maybe register it for standalone usage until someone finds time to implement it in Julia.

**Comment by timholy** [comment]
See https://github.com/JuliaLang/Pkg.jl/issues/810

**Comment by juliohm** [comment]
Interesting issue, thanks for sharing. My comment was more about maybe leaving EarthMoversDistance.jl the way it is as a separate package with a C dependency until someone finds the time to implement a pure Julia version?

Another issue is that the Earth movers distance has an original definition with probability distributions. Maybe one could define the distance in a package where non-parametric (histogram) distribution types are available. Perhaps Distances.jl or Distributions.jl would be more appropriate places for this algorithm? Hard to say. In any case, we could import a package like Distances.jl or Distributions.jl into ImageDistances.jl and wrap the algorithm to work with images.

**Comment by timholy** [comment]
There really isn't anything terribly image-specific here, if the main algorithm lives elsewhere that's pretty much it. Shall I close?

**Comment by juliohm** [comment]
The C dependency is a major downside, let's close it for now. We can get back to it in the future with more time to make it Julian. Thanks for raising the issue and for the reference implementation.

**Pull request closed without merging**
