### PR TITLE
implement psnr in ImageQualityIndexes module

### PR DESCRIPTION
**Pull request by johnnychen94**
Implement a `psnr` function in a new submodule `ImageQualityIndexes`.

I introduced a new type `ImageQualityIndex` since most indexes aren't even `PreMetric`, but I still take the same `evaluate` api (with a little expand on `args...`)

It's a new module, so I'd like to get some feedback from you.

* should `ImageQualityIndexes` be a standalone package?
* there's actually a `psnr` in `StatsBase`, should I expand the definition or just pretend there isn't?

### CODE REVIEW

**Comment by juliohm** [comment]
Hi Johnny,

Any reference that you could share about these indexes? I'm not familiar
with the problem and methods. How is it connected to computing distances
between images?

**Comment by johnnychen94** [comment]
The most famous PSNR is defined by log of mean squared error (aka Euclidean distance): `10log10(1/mse(x, ref))`

**Comment by juliohm** [comment]
So it is a problem where you are interested in computing a difference with
a reference image? Like computing a difference between original and
smoothed version? Any page on Wikipedia or book reference? If there are
many methods it may be reasonable to create a separate package. If I got
the problem right I don't think ImageDistances.jl is a good fit?

**Comment by johnnychen94** [comment]
> If there are many methods it may be reasonable to create a separate package

From what I've seen and heard, there're many (~5) widely used indexes. `psnr` and Structural Similarity Index `ssim` are two that I use them in my daily research.

Also, from what I've studied these years, finding a universally good image quality index(or loss) attracts many attentions, especially in the machine learning field. For example, the usage of perceptual losses (https://arxiv.org/abs/1603.08155) is widely studied last year, it's useful to let deep neural networks converges to a state that produces an image not only close to the reference image in distance sense but also visually good.

> If I got the problem right I don't think ImageDistances.jl is a good fit?

Classified by whether if an index need reference image `ref`, there're three typical indexes: need, partially-need, don't need. For those who need or partially needs `ref`(e.g., psnr), they work just like distances. For those who doesn't need, we can also expand 
 `evaluate(::NonReferenceImageQualityIndex, x)`

Perhaps the point is `ImageQualityIndexes` depend on `ImageDistances` and not the other way around. @timholy could you create a new package under JuliaImages?

**Comment by juliohm** [comment]
Yes, . I've used structural similarity before didn't know about this more
general term. I do think this problem depends on ImageDistances.jl and
shouldn't be a submodule.

**Comment by timholy** [comment]
https://github.com/JuliaImages/ImageQualityIndexes.jl. You've got full admin privileges.

**Comment by johnnychen94** [comment]
New dev goes to https://github.com/JuliaImages/ImageQualityIndexes.jl

close this now

**Pull request closed without merging**
